# Generated by Django 4.1.3 on 2022-11-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='class_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
