# Generated by Django 4.1.3 on 2022-11-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_classes_class_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='class_number',
            field=models.IntegerField(default='0', primary_key=True, serialize=False),
        ),
    ]
